{% set name = "doped" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SMTG-Bham/doped/archive/{{ version }}.tar.gz
  sha256: 3d9c0b191d204c68b7ecd8a64218be8b02c32f18b3173d8ca65ea69aeb38d91e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:  # TODO: Likely a number of updates here (pmg-core, mp-api etc) for doped v4
    - python >={{ python_min }}
    - tabulate
    - matplotlib-base >=3.5.2
    - numpy >=1.21.0
    - pymatgen >=2025.10.7  # LinearAssignment refactoring
    - pymatgen-analysis-defects >=2023.8.22
    - pydefect
    - shakenbreak >=3.3.4  # oxi-state functions renaming
    - pandas
    - filelock
    - cmcrameri >=1.4  # for colour-maps; >=1.4 required for cmcrameri.cm.cmaps definition
    - matplotlib-label-lines  # for labelling lines in matplotlib plots
    - dscribe  # for defect site guessing using SOAP analysis

test:
  requires:
    - python {{ python_min }}
  imports:
    - doped
    - pydefect  # test pydefect import, previously wasn't on conda-forge, required for eFNV correctiona and eigenvalue analysis

about:
  home: https://github.com/SMTG-Bham/doped
  license: MIT
  license_file: LICENSE
  summary: Python package to setup, process and analyse solid-state defect calculations/
  description: |
    doped is a Python software for the generation, pre-/post-processing and analysis of defect supercell calculations, implementing the defect simulation workflow in an efficient, reproducible, user-friendly yet powerful and fully-customisable manner.
  doc_url: https://doped.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-Bham/doped

extra:
  recipe-maintainers:
    - kavanase
